name: Fetch Car Ads Daily

on:
  schedule:
  - cron: '0 10 * * *'  # 10:00 UTC = 12:00 svensk sommartid
  workflow_dispatch:       # Gör att du kan starta det manuellt också

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Klona repo
        uses: actions/checkout@v3

      - name: 🐍 Installera Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Installera beroenden
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔐 Sätt miljövariabler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CAR_API_IDENTIFIER: ${{ secrets.CAR_API_IDENTIFIER }}
          CAR_API_KEY: ${{ secrets.CAR_API_KEY }}
        run: echo "Miljövariabler satta."

      - name: 🚀 Kör fetch-car-ads.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CAR_API_IDENTIFIER: ${{ secrets.CAR_API_IDENTIFIER }}
          CAR_API_KEY: ${{ secrets.CAR_API_KEY }}
        run: python fetch-car-ads.py
