name: Update Car Ads Daily

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC = 02:00 svensk sommartid
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Klona repo
        uses: actions/checkout@v3

      - name: 🐍 Installera Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Installera beroenden
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Kör update-car-ads.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CAR_API_IDENTIFIER: ${{ secrets.CAR_API_IDENTIFIER }}
          CAR_API_KEY: ${{ secrets.CAR_API_KEY }}
        run: python update-car-ads.py
